version: "3.6"
services:
  proxy:
    image: traefik
    command: --web --docker --logLevel=WARN
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
  prometheus:
    image: prom/prometheus:v2.3.2
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - './example/prometheus.yml:/etc/prometheus/prometheus.yml'
    links:
      - server:server
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
  server:
    image: 'node:8'
    working_dir: '/app'
    command: 'node example/index.js'
    volumes:
      - './package.json:/app/package.json'
      - './index.js:/app/index.js'
      - './example/example.js:/app/example/index.js'
      - './node_modules:/app/node_modules'
    ports:
      - 8080
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/example"
